name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Lint commit message
        run: yarn commitlint --from=HEAD~1

      - name: Build packages
        run: yarn build

      - name: Lint packages
        run: yarn lint

      - name: Test packages
        run: yarn test

      - name: Build flowtypes
        run: yarn build:flowtypes

      - name: Codecov
        uses: codecov/codecov-action@v2

  scripts:
    runs-on: macos-latest
    env:
      PACKAGE_NAME: test-${{ github.run_id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Create package
        run: |
          yarn create-package --package-name "@scope/${PACKAGE_NAME}-1" --template typescript-typescript
          yarn create-package --package-name="${PACKAGE_NAME}-2" --template=react-template --component-name=Test --dependencies=@littlespoon/theme --add-to-ui --add-to-storybook

      - name: Lint created packages
        run: yarn lerna run lint --scope="${PACKAGE_NAME}*"

      - name: Test created packages
        run: yarn lerna run test --scope="${PACKAGE_NAME}*"
