name: scripts
on: [push, pull_request]

jobs:
  scripts:
    runs-on: macos-latest
    env:
      PACKAGE_NAME: test_${{ github.run_id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Create package
        run: |
          yarn create-package --package-name "@scope/${PACKAGE_NAME}_1" --template typescript-template
          yarn create-package --package-name="${PACKAGE_NAME}_2" --template=react-template --component-name=Test --dependencies=@littlespoon/theme --add-to-ui --add-to-storybook

      - name: Lint created packages
        run: yarn lerna run lint --scope="${PACKAGE_NAME}*"

      - name: Test created packages
        run: yarn lerna run test --scope="${PACKAGE_NAME}*"
